/*
 * Copyright (c) 2024, Microchip
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/kernel.h>
#include <zephyr/linker/sections.h>

#define __mchp_bcfg_section_altcfg Z_GENERIC_SECTION(.mchp_bcfg_altcfg)
#define __mchp_bcfg_section_altcpn Z_GENERIC_SECTION(.mchp_bcfg_altcpn)
#define __mchp_bcfg_section_mark1  Z_GENERIC_SECTION(.mchp_bcfg_mark1)
#define __mchp_bcfg_section_devcfg Z_GENERIC_SECTION(.mchp_bcfg_devcfg)
#define __mchp_bcfg_section_cpn    Z_GENERIC_SECTION(.mchp_bcfg_cpn)
#define __mchp_bcfg_section_mark2  Z_GENERIC_SECTION(.mchp_bcfg_mark2)

typedef struct {
	/* Offset: 0x08 (R/W  32) ALT USERID */
	__IO uint32_t FUSES_ALTFUSERID;
	/* Offset: 0x0C (R/W  32) ALT CFGCON4 Fuses */
	__IO uint32_t FUSES_ALTDEVCFG4;
	/* Offset: 0x10 (R/W  32) ALT CFGCON2 Fuses */
	__IO uint32_t FUSES_ALTDEVCFG2;
	/* Offset: 0x14 (R/W  32) ALT CFGCON1 Fuses */
	__IO uint32_t FUSES_ALTDEVCFG1;
	/* Offset: 0x18 (R/W  32) ALT CFGCON0 Fuses */
	__IO uint32_t FUSES_ALTDEVCFG0;
	/* Offset: 0x1C (R/W  32) ALT NVR BCFG0 */
	__IO uint32_t FUSES_ALTFBCFG0;
} fuses_resgisters_altcfg_t;

typedef struct {
	/* Offset: 0x3C (R/W  32) ALT NVR CPN Register */
	__IO uint32_t FUSES_ALTFCPN0;
} fuses_resgisters_altcpn_t;

typedef struct {
	/* Offset: 0x108 (R/W  32) USER Page USERID */
	__IO uint32_t FUSES_FUSERID;
	/* Offset: 0x10C (R/W  32) USER Page CFGCON4 Fuses */
	__IO uint32_t FUSES_DEVCFG4;
	/* Offset: 0x110 (R/W  32) USER Page CFGCON2 Fuses */
	__IO uint32_t FUSES_DEVCFG2;
	/* Offset: 0x114 (R/W  32) USER Page CFGCON1 Fuses */
	__IO uint32_t FUSES_DEVCFG1;
	/* Offset: 0x118 (R/W  32) USER Page CFGCON0 Fuses */
	__IO uint32_t FUSES_DEVCFG0;
	/* Offset: 0x11C (R/W  32) NVR BCFG User Configuration Area */
	__IO uint32_t FUSES_FBCFG0;
} fuses_resgisters_devcfg_t;

typedef struct {
	/* Offset: 0x13C (R/W  32) NVR CPN Register */
	__IO uint32_t FUSES_FCPN0;
} fuses_resgisters_cpn_t;

typedef struct {
	__IO uint32_t FUSES_MARK;
} fuses_resgisters_mark_t;

fuses_resgisters_devcfg_t __mchp_bcfg_section_devcfg __mchp_fuses_config_devcfg = {

	/*** FUSERID ***/
	.FUSES_FUSERID = FUSES_FUSERID_USER_ID(CONFIG_FUSES_FUSERID),

	/*** DEVCFG4 ***/
	.FUSES_DEVCFG4 = (~FUSES_DEVCFG4_Msk & FUSES_DEVCFG4_RESETVALUE) |
			 FUSES_DEVCFG4_SOSCCFG(CONFIG_FUSES_DEVCFG4_SOSCCFG) |
			 FUSES_DEVCFG4_RTCEVENT_SEL(CONFIG_FUSES_DEVCFG4_RTCEVENT_SEL) |
			 FUSES_DEVCFG4_RTCEVENT_EN(CONFIG_FUSES_DEVCFG4_RTCEVENT_EN) |
			 FUSES_DEVCFG4_VBKP_1KCSEL(CONFIG_FUSES_DEVCFG4_VBKP_1KCSEL) |
			 FUSES_DEVCFG4_VBKP_32KCSEL(CONFIG_FUSES_DEVCFG4_VBKP_32KCSEL) |
			 FUSES_DEVCFG4_VBKP_DIVSEL(CONFIG_FUSES_DEVCFG4_VBKP_DIVSEL) |
			 FUSES_DEVCFG4_LPCLK_MOD(CONFIG_FUSES_DEVCFG4_LPCLK_MOD) |
			 FUSES_DEVCFG4_RTCEVTYPE(CONFIG_FUSES_DEVCFG4_RTCEVTYPE) |
			 FUSES_DEVCFG4_CPEN_DLY(CONFIG_FUSES_DEVCFG4_CPEN_DLY) |
			 FUSES_DEVCFG4_DSZPBOREN(CONFIG_FUSES_DEVCFG4_DSZPBOREN) |
			 FUSES_DEVCFG4_DSWDTPS(CONFIG_FUSES_DEVCFG4_DSWDTPS) |
			 FUSES_DEVCFG4_DSWDTOSC(CONFIG_FUSES_DEVCFG4_DSWDTOSC) |
			 FUSES_DEVCFG4_DSWDTEN(CONFIG_FUSES_DEVCFG4_DSWDTEN) |
			 FUSES_DEVCFG4_DSEN(CONFIG_FUSES_DEVCFG4_DSEN) |
			 FUSES_DEVCFG4_UVREGROVR(CONFIG_FUSES_DEVCFG4_UVREGROVR) |
			 FUSES_DEVCFG4_LPOSCEN(CONFIG_FUSES_DEVCFG4_LPOSCEN) |
			 FUSES_DEVCFG4_RTCNTM_CSEL(CONFIG_FUSES_DEVCFG4_RTCNTM_CSEL),

	/*** DEVCFG2 ***/
	.FUSES_DEVCFG2 = (~FUSES_DEVCFG2_Msk & FUSES_DEVCFG2_RESETVALUE) |
			 FUSES_DEVCFG2_ACMP_CYCLE(CONFIG_FUSES_DEVCFG2_ACMP_CYCLE) |
			 FUSES_DEVCFG2_DMTINTV(CONFIG_FUSES_DEVCFG2_DMTINTV) |
			 FUSES_DEVCFG2_PMUTEST_VDD_EN(CONFIG_FUSES_DEVCFG2_PMUTEST_VDD_EN) |
			 FUSES_DEVCFG2_POSCMOD(CONFIG_FUSES_DEVCFG2_POSCMOD) |
			 FUSES_DEVCFG2_WDTRMCS(CONFIG_FUSES_DEVCFG2_WDTRMCS) |
			 FUSES_DEVCFG2_SOSCSEL(CONFIG_FUSES_DEVCFG2_SOSCSEL) |
			 FUSES_DEVCFG2_WAKE2SPD(CONFIG_FUSES_DEVCFG2_WAKE2SPD) |
			 FUSES_DEVCFG2_CKSWEN(CONFIG_FUSES_DEVCFG2_CKSWEN) |
			 FUSES_DEVCFG2_FSCMEN(CONFIG_FUSES_DEVCFG2_FSCMEN) |
			 FUSES_DEVCFG2_WDTPSR(CONFIG_FUSES_DEVCFG2_WDTPSR) |
			 FUSES_DEVCFG2_WDTSPGM(CONFIG_FUSES_DEVCFG2_WDTSPGM) |
			 FUSES_DEVCFG2_WINDIS(CONFIG_FUSES_DEVCFG2_WINDIS) |
			 FUSES_DEVCFG2_WDTEN(CONFIG_FUSES_DEVCFG2_WDTEN) |
			 FUSES_DEVCFG2_WDTWINSZ(CONFIG_FUSES_DEVCFG2_WDTWINSZ) |
			 FUSES_DEVCFG2_DMTCNT(CONFIG_FUSES_DEVCFG2_DMTCNT) |
			 FUSES_DEVCFG2_DMTEN(CONFIG_FUSES_DEVCFG2_DMTEN),

	/*** DEVCFG1 ***/
	.FUSES_DEVCFG1 = (~FUSES_DEVCFG1_Msk & FUSES_DEVCFG1_RESETVALUE) |
			 FUSES_DEVCFG1_TRCEN(CONFIG_FUSES_DEVCFG1_TRCEN) |
			 FUSES_DEVCFG1_ECC_SEL_MEM(CONFIG_FUSES_DEVCFG1_ECC_SEL_MEM) |
			 FUSES_DEVCFG1_ZBTWKSYS(CONFIG_FUSES_DEVCFG1_ZBTWKSYS) |
			 FUSES_DEVCFG1_CMP0_OE(CONFIG_FUSES_DEVCFG1_CMP0_OE) |
			 FUSES_DEVCFG1_CMP1_OE(CONFIG_FUSES_DEVCFG1_CMP1_OE) |
			 FUSES_DEVCFG1_SLRCTRL0(CONFIG_FUSES_DEVCFG1_SLRCTRL0) |
			 FUSES_DEVCFG1_SLRCTRL1(CONFIG_FUSES_DEVCFG1_SLRCTRL1) |
			 FUSES_DEVCFG1_SLRCTRL2(CONFIG_FUSES_DEVCFG1_SLRCTRL2) |
			 FUSES_DEVCFG1_SMCLR(CONFIG_FUSES_DEVCFG1_SMCLR) |
			 FUSES_DEVCFG1_QSCHE_EN(CONFIG_FUSES_DEVCFG1_QSCHE_EN) |
			 FUSES_DEVCFG1_QSPI_HSEN(CONFIG_FUSES_DEVCFG1_QSPI_HSEN) |
			 FUSES_DEVCFG1_SCOM0_HSEN(CONFIG_FUSES_DEVCFG1_SCOM0_HSEN) |
			 FUSES_DEVCFG1_SCOM1_HSEN(CONFIG_FUSES_DEVCFG1_SCOM1_HSEN) |
			 FUSES_DEVCFG1_CCL_OE(CONFIG_FUSES_DEVCFG1_CCL_OE) |
			 FUSES_DEVCFG1_I2CDSEL0(CONFIG_FUSES_DEVCFG1_I2CDSEL0) |
			 FUSES_DEVCFG1_I2CDSEL1(CONFIG_FUSES_DEVCFG1_I2CDSEL1) |
			 FUSES_DEVCFG1_I2CDSEL2(CONFIG_FUSES_DEVCFG1_I2CDSEL2) |
			 FUSES_DEVCFG1_WDTPSS(CONFIG_FUSES_DEVCFG1_WDTPSS) |
			 FUSES_DEVCFG1_QSPIDDRM(CONFIG_FUSES_DEVCFG1_QSPIDDRM) |
			 FUSES_DEVCFG1_CLKZBREF(CONFIG_FUSES_DEVCFG1_CLKZBREF),

	/*** DEVCFG0 ***/
	.FUSES_DEVCFG0 = (~FUSES_DEVCFG0_Msk & FUSES_DEVCFG0_RESETVALUE) |
			 FUSES_DEVCFG0_SWOEN(CONFIG_FUSES_DEVCFG0_SWOEN) |
			 FUSES_DEVCFG0_TROEN(CONFIG_FUSES_DEVCFG0_TROEN) |
			 FUSES_DEVCFG0_ADCPOVR(CONFIG_FUSES_DEVCFG0_ADCPOVR) |
			 FUSES_DEVCFG0_ACCMP1_ALTEN(CONFIG_FUSES_DEVCFG0_ACCMP1_ALTEN) |
			 FUSES_DEVCFG0_CPENFILT(CONFIG_FUSES_DEVCFG0_CPENFILT) |
			 FUSES_DEVCFG0_RTCIN0_ALTEN(CONFIG_FUSES_DEVCFG0_RTCIN0_ALTEN) |
			 FUSES_DEVCFG0_RTCOUT_ALTEN(CONFIG_FUSES_DEVCFG0_RTCOUT_ALTEN) |
			 FUSES_DEVCFG0_SMBUSEN0(CONFIG_FUSES_DEVCFG0_SMBUSEN0) |
			 FUSES_DEVCFG0_SMBUSEN1(CONFIG_FUSES_DEVCFG0_SMBUSEN1) |
			 FUSES_DEVCFG0_HPLUGDIS(CONFIG_FUSES_DEVCFG0_HPLUGDIS) |
			 FUSES_DEVCFG0_SLRTEN0(CONFIG_FUSES_DEVCFG0_SLRTEN0) |
			 FUSES_DEVCFG0_SLRTEN1(CONFIG_FUSES_DEVCFG0_SLRTEN1) |
			 FUSES_DEVCFG0_SLRTEN2(CONFIG_FUSES_DEVCFG0_SLRTEN2) |
			 FUSES_DEVCFG0_PCM(CONFIG_FUSES_DEVCFG0_PCM) |
			 FUSES_DEVCFG0_INT0E(CONFIG_FUSES_DEVCFG0_INT0E) |
			 FUSES_DEVCFG0_INT0P(CONFIG_FUSES_DEVCFG0_INT0P) |
			 FUSES_DEVCFG0_FECCCON(CONFIG_FUSES_DEVCFG0_FECCCON) |
			 FUSES_DEVCFG0_FRECCDIS(CONFIG_FUSES_DEVCFG0_FRECCDIS),
	/*** FBCFG0 ***/
	.FUSES_FBCFG0 = (~FUSES_FBCFG0_Msk & FUSES_FBCFG0_RESETVALUE) |
			FUSES_FBCFG0_PCSCMODE(CONFIG_FUSES_FBCFG0_PCSCMODE) |
			FUSES_FBCFG0_BINFOVALID(CONFIG_FUSES_FBCFG0_BINFOVALID),
};

fuses_resgisters_cpn_t __mchp_bcfg_section_cpn __mchp_fuses_config_cpn = {
	/*** FCPN0 ***/
	.FUSES_FCPN0 = FUSES_FCPN0_CP(CONFIG_FUSES_FCPN0_CP),
};

fuses_resgisters_mark_t __mchp_bcfg_section_mark1 __mchp_fuses_config_mark1 = {
	.FUSES_MARK = 0x7FFFFFFF,
};

fuses_resgisters_mark_t __mchp_bcfg_section_mark2 __mchp_fuses_config_mark2 = {
	.FUSES_MARK = 0x7FFFFFFF,
};

fuses_resgisters_altcfg_t __mchp_bcfg_section_altcfg __mchp_fuses_config_altcfg = {
	/*** ALTFUSERID ***/
	.FUSES_ALTFUSERID = FUSES_FUSERID_USER_ID(FUSES_ALTFUSERID_RESETVALUE),

	/*** ALTDEVCFG4 ***/
	.FUSES_ALTDEVCFG4 = FUSES_ALTDEVCFG4_RESETVALUE,

	/*** ALTDEVCFG2 ***/
	.FUSES_ALTDEVCFG2 = FUSES_ALTDEVCFG2_RESETVALUE,

	/*** ALTDEVCFG1 ***/
	.FUSES_ALTDEVCFG1 = FUSES_ALTDEVCFG1_RESETVALUE,

	/*** ALTDEVCFG0 ***/
	.FUSES_ALTDEVCFG0 = FUSES_ALTDEVCFG0_RESETVALUE,

	/*** ALTFBCFG0 ***/
	.FUSES_ALTFBCFG0 = FUSES_ALTFBCFG0_RESETVALUE,
};

fuses_resgisters_altcpn_t __mchp_bcfg_section_altcpn __mchp_fuses_config_altcpn = {
	/*** ALTFCPN0 ***/
	.FUSES_ALTFCPN0 = FUSES_ALTFCPN0_RESETVALUE,
};
